# Generated by Django 4.2.7 on 2024-05-24 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0006_alter_audiofile_class_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiofile',
            name='zip_file',
            field=models.FileField(blank=True, null=True, upload_to='audio_zip/'),
        ),
    ]
