# Generated by Django 4.2.7 on 2024-05-24 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0007_audiofile_zip_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audiofile',
            name='zip_file',
        ),
        migrations.RemoveField(
            model_name='audiogrammatik_aktiv',
            name='audio_file',
        ),
        migrations.RemoveField(
            model_name='audiomenschen',
            name='audio_file',
        ),
        migrations.AddField(
            model_name='audiogrammatik_aktiv',
            name='zip_file',
            field=models.FileField(blank=True, null=True, upload_to='audio_zip/'),
        ),
        migrations.AddField(
            model_name='audiomenschen',
            name='zip_file',
            field=models.FileField(blank=True, null=True, upload_to='audio_zip/'),
        ),
    ]
